oc delete BuildConfig        selenium-base
oc delete BuildConfig        selenium-node-base
oc delete BuildConfig        selenium-hub
oc delete BuildConfig        selenium-node-firefox
oc delete BuildConfig        selenium-node-chrome
oc delete ImageStream       selenium-base
oc delete ImageStream       selenium-node-base
oc delete ImageStream       selenium-hub
oc delete ImageStream       selenium-node-firefox
oc delete ImageStream       selenium-node-chrome
